# Generated by Django 6.0.2 on 2026-02-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_remove_staff_name_remove_staff_phone_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('ADMITTED', 'Admitted'), ('DISCHARGED', 'Discharged'), ('TRANSFERRED', 'Transferred')], default='ADMITTED', max_length=20),
        ),
    ]
