# Generated by Django 6.0.2 on 2026-02-25 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_admission_status'),
        ('users', '0007_alter_user_first_name_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='users.doctor'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.bed'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.room'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_bills', to='facility.admission'),
        ),
    ]
