# Generated by Django 6.0.2 on 2026-02-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_admission_doctor_alter_admission_bed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied')], default='AVAILABLE', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('room', 'bed_number')},
        ),
    ]
