# Generated by Django 6.0.2 on 2026-02-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0006_staff_dept_stafftask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffTask',
        ),
    ]
