# Generated by Django 6.0.2 on 2026-03-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0007_delete_stafftask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='total_days',
        ),
        migrations.AddField(
            model_name='admission',
            name='total_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
