# Generated by Django 6.0.2 on 2026-03-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0008_remove_room_total_days_admission_total_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffassignment',
            name='acuity_level',
        ),
    ]
