# Generated by Django 6.0.2 on 2026-02-24 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_alter_department_hod'),
        ('users', '0003_alter_user_created_at_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='users.doctor'),
        ),
    ]
