# Generated by Django 6.0.2 on 2026-02-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_labreport_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labreport',
            name='created_by',
        ),
    ]
