# Generated by Django 6.0.2 on 2026-02-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_created_at_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
